const EXT2_VALID_FS : u16 = 1;
const EXT2_ERROR_FS : u16 = 2;

const EXT2_ERRORS_CONTINUE : u16 = 1;
const EXT2_ERRORS_RO : u16 = 2;
const EXT2_ERRORS_PANIC : u16 = 3;


enum EXT2_OS {
    EXT2_OS_LINUX,
    EXT2_OS_HURD,
    EXT2_OS_MASIX,
    EXT2_OS_FREEBSD,
    EXT2_OS_LITES
}

enum EXT2_FEATURE_COMPAT {
    EXT2_FEATURE_COMPAT_DIR_PREALLOC,
    EXT2_FEATURE_COMPAT_IMAGIC_INODES,
    EXT3_FEATURE_COMPAT_HAS_JOURNAL,
    EXT2_FEATURE_COMPAT_EXT_ATTR,
    EXT2_FEATURE_COMPAT_RESIZE_INO,
    EXT2_FEATURE_COMPAT_DIR_INDEX
}

enum EXT2_FEATURE_INCOMPAT {
    EXT2_FEATURE_INCOMPAT_COMPRESSION,
    EXT2_FEATURE_INCOMPAT_FILETYPE,
    EXT3_FEATURE_INCOMPAT_RECOVER,
    EXT3_FEATURE_INCOMPAT_JOURNAL_DEV,
    EXT2_FEATURE_INCOMPAT_META_BG
}

enum EXT2_FEATURE_RO_COMPAT {
    EXT2_FEATURE_RO_COMPAT_SPARSE_SUPER,
    EXT2_FEATURE_RO_COMPAT_LARGE_FILE,
    EXT2_FEATURE_RO_COMPAT_BTREE_DIR
}

enum EXT2_ALG {
    EXT2_LZV1_ALG,
    EXT2_LZRW3A_ALG,
    EXT2_GZIP_ALG,
    EXT2_BZIP2_ALG,
    EXT2_LZO_ALG
}


enum EXT2_S_IF {
    EXT2_S_IFSOCK,
    EXT2_S_IFLNK,
    EXT2_S_IFREG,
    EXT2_S_IFBLK,
    EXT2_S_IFDIR,
    EXT2_S_IFCHR,
    EXT2_S_IFIFO
}

enum EXT2_S_IS {
    EXT2_S_ISUID,
    EXT2_S_ISGID,
    EXT2_S_ISVTX
}

enum EXT2_S_I {
    EXT2_S_IRUSR,
    EXT2_S_IWUSR,
    EXT2_S_IXUSR,
    EXT2_S_IRGRP,
    EXT2_S_IWGRP,
    EXT2_S_IXGRP,
    EXT2_S_IROTH,
    EXT2_S_IWOTH,
    EXT2_S_IXOTH,

}

enum EXT2_FL {

}

